task  SA
self.device  cuda
/home/lcur1101/ATCS_group3/marc_data/dataset_fr_train.json
Traceback (most recent call last):
  File "/home/lcur1101/ATCS_group3/code/pipeline_file.py", line 219, in <module>
    acc = pipeline(LM_model, task, prompt_generator)
  File "/home/lcur1101/ATCS_group3/code/pipeline_file.py", line 106, in pipeline
    train_dataloader = create_dataloader(
  File "/home/lcur1101/ATCS_group3/code/dataloaders.py", line 80, in create_dataloader
    sample_texts, sample_labels = marc_dataset.get_random_sample(
  File "/home/lcur1101/ATCS_group3/code/dataloaders.py", line 60, in get_random_sample
    with open(self.data_path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lcur1101/ATCS_group3/marc_data/dataset_fr_train.json'
srun: error: r35n4: task 0: Exited with exit code 1
